import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export async function GET(req: NextRequest, { params }: { params: { bidId: string } }) {
  try {
    const bid = await prisma.bid.findUnique({
      where: { id: params.bidId },
      include: {
        tender: { include: { department: true, requirements: { orderBy: { requirementCode: 'asc' } } } },
        complianceResults: { include: { requirement: true } },
      },
    });

    if (!bid) {
      return NextResponse.json({ success: false, error: { message: 'Bid not found' } }, { status: 404 });
    }

    // Create official PDF using pdf-lib
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([612, 792]);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);

    // Helper to sanitize text for StandardFonts.Helvetica (WinAnsi)
    const cleanText = (str: string) => (str || '').replace(/[^\x20-\x7E]/g, '-').trim();

    // Header bar
    page.drawRectangle({
      x: 0,
      y: 730,
      width: 612,
      height: 62,
      color: rgb(0.043, 0.227, 0.356), // #0B3A5B
    });

    page.drawText('BIDSHIELD AI - COMPLIANCE & RISK ASSESSMENT REPORT', {
      x: 40,
      y: 755,
      size: 14,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText('Ministry of Petroleum & Natural Gas - Smart Procurement Intelligence System', {
      x: 40,
      y: 740,
      size: 9,
      font: fontRegular,
      color: rgb(0.95, 0.7, 0.0),
    });

    // Content Body
    let y = 690;
    page.drawText(`Tender Number: ${cleanText(bid.tender.tenderNumber)}`, { x: 40, y, size: 10, font: fontBold });
    page.drawText(`Date Generated: ${new Date().toISOString().split('T')[0]}`, { x: 400, y, size: 10, font: fontRegular });
    y -= 18;
    page.drawText(`Tender Title: ${cleanText(bid.tender.title).substring(0, 75)}`, { x: 40, y, size: 10, font: fontRegular });
    y -= 18;
    page.drawText(`Bidder Name: ${cleanText(bid.bidderName)}`, { x: 40, y, size: 11, font: fontBold, color: rgb(0.043, 0.227, 0.356) });
    y -= 25;

    // Summary Box
    page.drawRectangle({
      x: 40,
      y: y - 50,
      width: 532,
      height: 60,
      color: rgb(0.96, 0.97, 0.98),
      borderColor: rgb(0.8, 0.85, 0.9),
      borderWidth: 1,
    });

    page.drawText(`OVERALL COMPLIANCE SCORE: ${bid.complianceScore}%`, {
      x: 55,
      y: y - 20,
      size: 12,
      font: fontBold,
      color: bid.complianceScore >= 80 ? rgb(0.07, 0.54, 0.29) : rgb(0.85, 0.5, 0.0),
    });

    page.drawText(`RISK SCORE: ${bid.riskScore} / 100 (${cleanText(bid.riskLevel)} RISK)`, {
      x: 320,
      y: y - 20,
      size: 12,
      font: fontBold,
      color: bid.riskLevel === 'LOW' ? rgb(0.07, 0.54, 0.29) : bid.riskLevel === 'MEDIUM' ? rgb(0.85, 0.5, 0.0) : rgb(0.77, 0.15, 0.15),
    });

    page.drawText(`Final Status: ${cleanText(bid.finalReviewStatus)}`, { x: 55, y: y - 40, size: 10, font: fontRegular });

    y -= 80;
    page.drawText('REQUIREMENT EVALUATION MATRIX', { x: 40, y, size: 11, font: fontBold });
    y -= 20;

    // Table Header
    page.drawRectangle({ x: 40, y: y - 5, width: 532, height: 20, color: rgb(0.07, 0.38, 0.62) });
    page.drawText('Req Code', { x: 50, y, size: 9, font: fontBold, color: rgb(1, 1, 1) });
    page.drawText('Requirement Title', { x: 110, y, size: 9, font: fontBold, color: rgb(1, 1, 1) });
    page.drawText('Category', { x: 300, y, size: 9, font: fontBold, color: rgb(1, 1, 1) });
    page.drawText('Status', { x: 420, y, size: 9, font: fontBold, color: rgb(1, 1, 1) });
    page.drawText('Score', { x: 520, y, size: 9, font: fontBold, color: rgb(1, 1, 1) });

    y -= 22;

    for (const cr of bid.complianceResults) {
      if (y < 120) break;
      const req = cr.requirement;
      page.drawText(cleanText(req.requirementCode), { x: 50, y, size: 9, font: fontBold });
      page.drawText(cleanText(req.title).substring(0, 32), { x: 110, y, size: 8.5, font: fontRegular });
      page.drawText(cleanText(req.category), { x: 300, y, size: 8.5, font: fontRegular });
      page.drawText(cleanText(cr.status), {
        x: 420,
        y,
        size: 8.5,
        font: fontBold,
        color: cr.status === 'COMPLIANT' ? rgb(0.07, 0.54, 0.29) : cr.status === 'MISSING' ? rgb(0.77, 0.15, 0.15) : rgb(0.85, 0.5, 0.0),
      });
      page.drawText(`${cr.score}%`, { x: 520, y, size: 8.5, font: fontRegular });
      y -= 18;
    }

    // Disclaimer
    page.drawRectangle({ x: 40, y: 35, width: 532, height: 40, color: rgb(0.98, 0.98, 0.98) });
    page.drawText(
      'LEGAL DISCLAIMER: This report is an AI-assisted decision-support document generated by BidShield AI.',
      { x: 45, y: 60, size: 7.5, font: fontBold, color: rgb(0.4, 0.4, 0.4) }
    );
    page.drawText(
      'Final procurement decision remains strictly with the authorized government procurement officer (Human in the Loop).',
      { x: 45, y: 48, size: 7.5, font: fontRegular, color: rgb(0.4, 0.4, 0.4) }
    );

    const pdfBytes = await pdfDoc.save();
    const pdfBuffer = Buffer.from(pdfBytes);

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="BidShield_Compliance_Report_${bid.bidderName.replace(/\s+/g, '_')}.pdf"`,
      },
    });
  } catch (error: any) {
    console.error('PDF generation error:', error);
    return NextResponse.json({ success: false, error: { message: error.message } }, { status: 500 });
  }
}
